name: todomvc_objectory_indexeddb
description: TodoMVC built with Web Components. Persistency added through Objectory on IndexedDB
version: 0.0.2
dependencies:
  web_ui:
    git: https://github.com/dart-lang/web-ui.git
  objectory:
    git: https://github.com/vadimtsushko/objectory.git
